namespace Tests.Application.SetBookContent
{
    public static class FakeBook
    {
        public static string Content => @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pellentesque nisl lectus, ut malesuada augue molestie et. Etiam fermentum tincidunt rhoncus. Nulla facilisi. Nulla interdum leo nulla, nec faucibus libero aliquam et. Sed at scelerisque augue. Ut dignissim pulvinar diam id dapibus. Ut non diam porttitor, hendrerit lorem sit amet, tincidunt nunc. Nam bibendum imperdiet ipsum quis ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris sodales urna ut ex congue, sodales mollis risus bibendum. Curabitur iaculis luctus lorem. Donec vel vehicula odio.

Praesent vulputate eleifend tortor, eget elementum quam aliquet sit amet. Curabitur ante elit, mattis condimentum finibus ut, ullamcorper id nulla. Cras condimentum nibh massa, sed vulputate nunc mollis sit amet. Suspendisse tempus convallis risus, non efficitur eros condimentum vitae. Integer eu lorem pulvinar, fermentum felis nec, suscipit augue. Praesent tincidunt varius magna non aliquet. Nulla ut fringilla ante. Nulla maximus semper sapien, nec facilisis ligula.

Quisque aliquet commodo varius. Sed euismod magna finibus metus accumsan, eu tempor lorem gravida. Praesent urna odio, tempor id nisi consequat, laoreet dapibus ipsum. Aliquam pulvinar tempus iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut varius justo at libero pharetra, at semper turpis bibendum. Mauris ullamcorper congue volutpat. Etiam eget diam non metus consequat pharetra quis at augue. Sed finibus sapien id erat sollicitudin, non dapibus dolor gravida. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nunc sed mi pellentesque, fermentum odio ac, accumsan diam. Morbi elementum risus velit, in dictum orci pulvinar non. Suspendisse tempor ornare sem, eu sodales erat aliquam sit amet. In aliquam orci in dignissim aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam posuere purus orci. Praesent in magna nulla. Quisque in nisi ornare, malesuada nunc sed, interdum velit. Nunc orci libero, molestie eget purus sed, euismod volutpat tellus. Nullam metus massa, consequat sit amet dui et, tempor auctor lectus. Duis sollicitudin non odio ornare tristique. Maecenas vel luctus justo.

Cras felis leo, sollicitudin fermentum nunc eget, mattis pellentesque tellus. Nulla tempor felis ac nulla luctus, at fringilla nulla luctus. Nunc euismod lacus eget purus convallis vestibulum. Etiam dapibus sapien consectetur quam gravida tristique. Morbi mauris neque, vehicula non orci vel, fermentum vehicula enim. Quisque sapien lorem, dapibus vitae enim sed, porttitor ornare justo. Aliquam erat volutpat. Pellentesque id tristique velit. Ut pellentesque nibh at arcu pretium tempus. Nullam vitae enim sodales, dapibus enim ac, rutrum tortor. Maecenas pharetra vitae nisl eu eleifend. Aenean metus magna, fringilla ac mauris vitae, luctus vehicula dui.";
    }
}